/** ASCII-only codes returned in login Server Action payloads (Flight-safe). */
export const AuthErrorCode = {
  MISSING_WHATSAPP: "MISSING_WHATSAPP",
  INVALID_WHATSAPP: "INVALID_WHATSAPP",
  SUPABASE_ENV_MISSING: "SUPABASE_ENV_MISSING",
  SUPABASE_CONNECTION_ERROR: "SUPABASE_CONNECTION_ERROR",
  SUPABASE_PROFILE_FETCH_FAILED: "SUPABASE_PROFILE_FETCH_FAILED",
  TEACHER_CODE_REQUIRED: "TEACHER_CODE_REQUIRED",
  INVALID_TEACHER_CODE: "INVALID_TEACHER_CODE",
  SUPABASE_PROFILE_CREATE_FAILED: "SUPABASE_PROFILE_CREATE_FAILED",
  SUPABASE_STUDENT_LINK_FAILED: "SUPABASE_STUDENT_LINK_FAILED",
  SUPABASE_SESSION_UPDATE_FAILED: "SUPABASE_SESSION_UPDATE_FAILED",
  SESSION_SAVE_FAILED: "SESSION_SAVE_FAILED",
  LOGIN_UNEXPECTED: "LOGIN_UNEXPECTED",
  ACCOUNT_PENDING_VERIFICATION: "ACCOUNT_PENDING_VERIFICATION",
  MISSING_FULL_NAME: "MISSING_FULL_NAME",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  OTP_UNAVAILABLE: "OTP_UNAVAILABLE",
  OTP_INVALID: "OTP_INVALID",
  OTP_REPLAY: "OTP_REPLAY",
  REGISTER_REQUIRED: "REGISTER_REQUIRED",
  ADMIN_FALLBACK_DENIED: "ADMIN_FALLBACK_DENIED",
  DEMO_BYPASS_DISABLED: "DEMO_BYPASS_DISABLED",
  /** [AUTH-007] Teacher inactive or student fully deactivated */
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  /** [AUTH-009] Teacher login recovery */
  INVALID_EMAIL: "INVALID_EMAIL",
  TEACHER_NOT_FOUND: "TEACHER_NOT_FOUND",
  RECOVERY_RATE_LIMITED: "RECOVERY_RATE_LIMITED",
  MAIL_SEND_FAILED: "MAIL_SEND_FAILED",
  RESET_INVALID: "RESET_INVALID",
  MAGIC_INVALID: "MAGIC_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
} as const;

export type AuthErrorCode =
  (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

export function logAuthFailure(context: string, error: unknown): void {
  console.error("SERVER_AUTH_FAILURE:", context, error);
}

export function authError(code: AuthErrorCode): {
  status: "error";
  code: AuthErrorCode;
} {
  return { status: "error", code };
}
